# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}
branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\bsscript

# scripts that run after cloning repository
install:
  - cmd: C:\MinGW\bin\mingw32-make.exe C:\bsscript\Makefile.win
  
build: off

test_script:
  - cmd: C:\bsscript\bin\bss.exe
